sudo: required
language: node_js
node_js:
  - "10.15.1"
services:
  - docker
dist: trusty
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli

script:
- ng lint
- ng build
- docker build -t rbelmeha/angular-redux .

deploy:
  provider: Heroku
  api_key:
    secure: HEROKU_API
  app: docker-angular-redux
 ###  on:
  ###   repo: blarvin/TEAM-MALN-ACEBOOK ### YOUR REPO IS HERE
